# Generated by Django 2.1.7 on 2019-04-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Value of element', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('parentID', models.PositiveIntegerField()),
                ('level', models.PositiveIntegerField()),
            ],
        ),
    ]
