# Generated by Django 2.1.7 on 2019-04-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
