# Generated by Django 2.1.7 on 2019-04-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitDB', '0002_element_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='created',
        ),
        migrations.AddField(
            model_name='element',
            name='changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
